### ISSUE TITLE
Integration with Bluemix

### ISSUE THREAD

**Issue by tokidoki11** [softlayer/softlayer-object-storage-php#33]
Is this compatible with bluemix?
I tried to do credentials and pull my container

this always come
Fatal error: Uncaught ObjectStorage_Exception_Http_NotFound: Not Found in /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage.php:166 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage.php(166): ObjectStorage_Exception_Http::factory('Not Found', 404) #1 /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage.php(94): ObjectStorage->authenticate() #2 /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage.php(604): ObjectStorage->getAuthenticationData() #3 /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage/Abstract.php(608): ObjectStorage->delete(Object(ObjectStorage_Container)) #4 /Applications/XAMPP/xamppfiles/htdocs/jti-ats/test.php(18): ObjectStorage_Abstract->delete() #5 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/jti-ats/vendor/softlayer/objectstorage/lib/ObjectStorage.php on line 166

**Comment by tokidoki11** [comment]
I use this package "php-opencloud/openstack"
